name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        folder: build
        
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: matiasrodrigocabrera@gmail.com
        heroku_app_name: githubactions-demo
        branch: main
